/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectViewerRouteRouteImport } from './routes/_authenticated/project-viewer/route'
import { Route as AuthenticatedMiniAdminRouteRouteImport } from './routes/_authenticated/mini-admin/route'
import { Route as AuthenticatedEngineerRouteRouteImport } from './routes/_authenticated/engineer/route'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/client/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAccountantRouteRouteImport } from './routes/_authenticated/accountant/route'
import { Route as AuthenticatedProjectViewerIndexRouteImport } from './routes/_authenticated/project-viewer/index'
import { Route as AuthenticatedEngineerIndexRouteImport } from './routes/_authenticated/engineer/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAccountantIndexRouteImport } from './routes/_authenticated/accountant/index'
import { Route as AuthenticatedProjectViewerProjectIdRouteImport } from './routes/_authenticated/project-viewer/$projectId'
import { Route as AuthenticatedEngineerProjectIdRouteImport } from './routes/_authenticated/engineer/$projectId'
import { Route as AuthenticatedClientNewRouteImport } from './routes/_authenticated/client/new'
import { Route as AuthenticatedClientProjectIdRouteImport } from './routes/_authenticated/client/$projectId'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin/vendors'
import { Route as AuthenticatedAdminTodosRouteImport } from './routes/_authenticated/admin/todos'
import { Route as AuthenticatedAdminAnalysisRouteImport } from './routes/_authenticated/admin/analysis'
import { Route as AuthenticatedAccountantVendorPaymentsRouteImport } from './routes/_authenticated/accountant/vendor-payments'
import { Route as AuthenticatedAccountantReportsRouteImport } from './routes/_authenticated/accountant/reports'
import { Route as AuthenticatedAccountantReconcileRouteImport } from './routes/_authenticated/accountant/reconcile'
import { Route as AuthenticatedAccountantPaymentsRouteImport } from './routes/_authenticated/accountant/payments'
import { Route as AuthenticatedAccountantInvoicesRouteImport } from './routes/_authenticated/accountant/invoices'
import { Route as AuthenticatedAccountantCashbookRouteImport } from './routes/_authenticated/accountant/cashbook'
import { Route as AuthenticatedAccountantBillsRouteImport } from './routes/_authenticated/accountant/bills'
import { Route as AuthenticatedAccountantBankImportRouteImport } from './routes/_authenticated/accountant/bank-import'
import { Route as AuthenticatedAccountantBankAccountsRouteImport } from './routes/_authenticated/accountant/bank-accounts'
import { Route as AuthenticatedAccountantAnalysisRouteImport } from './routes/_authenticated/accountant/analysis'
import { Route as AuthenticatedAccountantAccountsRouteImport } from './routes/_authenticated/accountant/accounts'
import { Route as AuthenticatedMiniAdminEngineerIndexRouteImport } from './routes/_authenticated/mini-admin/Engineer/index'
import { Route as AuthenticatedMiniAdminDashboardIndexRouteImport } from './routes/_authenticated/mini-admin/Dashboard/index'
import { Route as AuthenticatedMiniAdminTodoTodoRouteImport } from './routes/_authenticated/mini-admin/Todo/todo'
import { Route as AuthenticatedMiniAdminEngineerProjectIdRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId'
import { Route as AuthenticatedMiniAdminAdminVendorsRouteImport } from './routes/_authenticated/mini-admin/Admin/vendors'
import { Route as AuthenticatedMiniAdminAdminAnalysisRouteImport } from './routes/_authenticated/mini-admin/Admin/analysis'
import { Route as AuthenticatedEngineerProjectIdWorksheetRouteImport } from './routes/_authenticated/engineer/$projectId.worksheet'
import { Route as AuthenticatedEngineerProjectIdQuotationRouteImport } from './routes/_authenticated/engineer/$projectId.quotation'
import { Route as AuthenticatedEngineerProjectIdMessagesRouteImport } from './routes/_authenticated/engineer/$projectId.messages'
import { Route as AuthenticatedEngineerProjectIdInspectionRouteImport } from './routes/_authenticated/engineer/$projectId.inspection'
import { Route as AuthenticatedEngineerProjectIdCompareRouteImport } from './routes/_authenticated/engineer/$projectId.compare'
import { Route as AuthenticatedMiniAdminAdminProjectViewersIndexRouteImport } from './routes/_authenticated/mini-admin/Admin/ProjectViewers/index'
import { Route as AuthenticatedMiniAdminAdminClientsIndexRouteImport } from './routes/_authenticated/mini-admin/Admin/Clients/index'
import { Route as AuthenticatedMiniAdminEngineerProjectIdWorksheetRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.worksheet'
import { Route as AuthenticatedMiniAdminEngineerProjectIdQuotationRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.quotation'
import { Route as AuthenticatedMiniAdminEngineerProjectIdMessagesRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.messages'
import { Route as AuthenticatedMiniAdminEngineerProjectIdInspectionRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.inspection'
import { Route as AuthenticatedMiniAdminEngineerProjectIdCompareRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.compare'
import { Route as AuthenticatedMiniAdminAdminClientsNewRouteImport } from './routes/_authenticated/mini-admin/Admin/Clients/new'
import { Route as AuthenticatedMiniAdminAdminClientsProjectIdRouteImport } from './routes/_authenticated/mini-admin/Admin/Clients/$projectId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectViewerRouteRoute =
  AuthenticatedProjectViewerRouteRouteImport.update({
    id: '/project-viewer',
    path: '/project-viewer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiniAdminRouteRoute =
  AuthenticatedMiniAdminRouteRouteImport.update({
    id: '/mini-admin',
    path: '/mini-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngineerRouteRoute =
  AuthenticatedEngineerRouteRouteImport.update({
    id: '/engineer',
    path: '/engineer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountantRouteRoute =
  AuthenticatedAccountantRouteRouteImport.update({
    id: '/accountant',
    path: '/accountant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectViewerIndexRoute =
  AuthenticatedProjectViewerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectViewerRouteRoute,
  } as any)
const AuthenticatedEngineerIndexRoute =
  AuthenticatedEngineerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEngineerRouteRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAccountantIndexRoute =
  AuthenticatedAccountantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedProjectViewerProjectIdRoute =
  AuthenticatedProjectViewerProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectViewerRouteRoute,
  } as any)
const AuthenticatedEngineerProjectIdRoute =
  AuthenticatedEngineerProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedEngineerRouteRoute,
  } as any)
const AuthenticatedClientNewRoute = AuthenticatedClientNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientRouteRoute,
} as any)
const AuthenticatedClientProjectIdRoute =
  AuthenticatedClientProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTodosRoute = AuthenticatedAdminTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalysisRoute =
  AuthenticatedAdminAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAccountantVendorPaymentsRoute =
  AuthenticatedAccountantVendorPaymentsRouteImport.update({
    id: '/vendor-payments',
    path: '/vendor-payments',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantReportsRoute =
  AuthenticatedAccountantReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantReconcileRoute =
  AuthenticatedAccountantReconcileRouteImport.update({
    id: '/reconcile',
    path: '/reconcile',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantPaymentsRoute =
  AuthenticatedAccountantPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantInvoicesRoute =
  AuthenticatedAccountantInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantCashbookRoute =
  AuthenticatedAccountantCashbookRouteImport.update({
    id: '/cashbook',
    path: '/cashbook',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantBillsRoute =
  AuthenticatedAccountantBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantBankImportRoute =
  AuthenticatedAccountantBankImportRouteImport.update({
    id: '/bank-import',
    path: '/bank-import',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantBankAccountsRoute =
  AuthenticatedAccountantBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantAnalysisRoute =
  AuthenticatedAccountantAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedAccountantAccountsRoute =
  AuthenticatedAccountantAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAccountantRouteRoute,
  } as any)
const AuthenticatedMiniAdminEngineerIndexRoute =
  AuthenticatedMiniAdminEngineerIndexRouteImport.update({
    id: '/Engineer/',
    path: '/Engineer/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminDashboardIndexRoute =
  AuthenticatedMiniAdminDashboardIndexRouteImport.update({
    id: '/Dashboard/',
    path: '/Dashboard/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminTodoTodoRoute =
  AuthenticatedMiniAdminTodoTodoRouteImport.update({
    id: '/Todo/todo',
    path: '/Todo/todo',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdRoute =
  AuthenticatedMiniAdminEngineerProjectIdRouteImport.update({
    id: '/Engineer/$projectId',
    path: '/Engineer/$projectId',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminVendorsRoute =
  AuthenticatedMiniAdminAdminVendorsRouteImport.update({
    id: '/Admin/vendors',
    path: '/Admin/vendors',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminAnalysisRoute =
  AuthenticatedMiniAdminAdminAnalysisRouteImport.update({
    id: '/Admin/analysis',
    path: '/Admin/analysis',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedEngineerProjectIdWorksheetRoute =
  AuthenticatedEngineerProjectIdWorksheetRouteImport.update({
    id: '/worksheet',
    path: '/worksheet',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdQuotationRoute =
  AuthenticatedEngineerProjectIdQuotationRouteImport.update({
    id: '/quotation',
    path: '/quotation',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdMessagesRoute =
  AuthenticatedEngineerProjectIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdInspectionRoute =
  AuthenticatedEngineerProjectIdInspectionRouteImport.update({
    id: '/inspection',
    path: '/inspection',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdCompareRoute =
  AuthenticatedEngineerProjectIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminAdminProjectViewersIndexRoute =
  AuthenticatedMiniAdminAdminProjectViewersIndexRouteImport.update({
    id: '/Admin/ProjectViewers/',
    path: '/Admin/ProjectViewers/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsIndexRoute =
  AuthenticatedMiniAdminAdminClientsIndexRouteImport.update({
    id: '/Admin/Clients/',
    path: '/Admin/Clients/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute =
  AuthenticatedMiniAdminEngineerProjectIdWorksheetRouteImport.update({
    id: '/worksheet',
    path: '/worksheet',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdQuotationRoute =
  AuthenticatedMiniAdminEngineerProjectIdQuotationRouteImport.update({
    id: '/quotation',
    path: '/quotation',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdMessagesRoute =
  AuthenticatedMiniAdminEngineerProjectIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdInspectionRoute =
  AuthenticatedMiniAdminEngineerProjectIdInspectionRouteImport.update({
    id: '/inspection',
    path: '/inspection',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdCompareRoute =
  AuthenticatedMiniAdminEngineerProjectIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsNewRoute =
  AuthenticatedMiniAdminAdminClientsNewRouteImport.update({
    id: '/Admin/Clients/new',
    path: '/Admin/Clients/new',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsProjectIdRoute =
  AuthenticatedMiniAdminAdminClientsProjectIdRouteImport.update({
    id: '/Admin/Clients/$projectId',
    path: '/Admin/Clients/$projectId',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accountant': typeof AuthenticatedAccountantRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/engineer': typeof AuthenticatedEngineerRouteRouteWithChildren
  '/mini-admin': typeof AuthenticatedMiniAdminRouteRouteWithChildren
  '/project-viewer': typeof AuthenticatedProjectViewerRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/accountant/accounts': typeof AuthenticatedAccountantAccountsRoute
  '/accountant/analysis': typeof AuthenticatedAccountantAnalysisRoute
  '/accountant/bank-accounts': typeof AuthenticatedAccountantBankAccountsRoute
  '/accountant/bank-import': typeof AuthenticatedAccountantBankImportRoute
  '/accountant/bills': typeof AuthenticatedAccountantBillsRoute
  '/accountant/cashbook': typeof AuthenticatedAccountantCashbookRoute
  '/accountant/invoices': typeof AuthenticatedAccountantInvoicesRoute
  '/accountant/payments': typeof AuthenticatedAccountantPaymentsRoute
  '/accountant/reconcile': typeof AuthenticatedAccountantReconcileRoute
  '/accountant/reports': typeof AuthenticatedAccountantReportsRoute
  '/accountant/vendor-payments': typeof AuthenticatedAccountantVendorPaymentsRoute
  '/admin/analysis': typeof AuthenticatedAdminAnalysisRoute
  '/admin/todos': typeof AuthenticatedAdminTodosRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/client/new': typeof AuthenticatedClientNewRoute
  '/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/project-viewer/$projectId': typeof AuthenticatedProjectViewerProjectIdRoute
  '/accountant/': typeof AuthenticatedAccountantIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/engineer/': typeof AuthenticatedEngineerIndexRoute
  '/project-viewer/': typeof AuthenticatedProjectViewerIndexRoute
  '/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/analysis': typeof AuthenticatedMiniAdminAdminAnalysisRoute
  '/mini-admin/Admin/vendors': typeof AuthenticatedMiniAdminAdminVendorsRoute
  '/mini-admin/Engineer/$projectId': typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  '/mini-admin/Todo/todo': typeof AuthenticatedMiniAdminTodoTodoRoute
  '/mini-admin/Dashboard/': typeof AuthenticatedMiniAdminDashboardIndexRoute
  '/mini-admin/Engineer/': typeof AuthenticatedMiniAdminEngineerIndexRoute
  '/mini-admin/Admin/Clients/$projectId': typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  '/mini-admin/Admin/Clients/new': typeof AuthenticatedMiniAdminAdminClientsNewRoute
  '/mini-admin/Engineer/$projectId/compare': typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  '/mini-admin/Engineer/$projectId/inspection': typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  '/mini-admin/Engineer/$projectId/messages': typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  '/mini-admin/Engineer/$projectId/quotation': typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  '/mini-admin/Engineer/$projectId/worksheet': typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/Clients/': typeof AuthenticatedMiniAdminAdminClientsIndexRoute
  '/mini-admin/Admin/ProjectViewers/': typeof AuthenticatedMiniAdminAdminProjectViewersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/mini-admin': typeof AuthenticatedMiniAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/accountant/accounts': typeof AuthenticatedAccountantAccountsRoute
  '/accountant/analysis': typeof AuthenticatedAccountantAnalysisRoute
  '/accountant/bank-accounts': typeof AuthenticatedAccountantBankAccountsRoute
  '/accountant/bank-import': typeof AuthenticatedAccountantBankImportRoute
  '/accountant/bills': typeof AuthenticatedAccountantBillsRoute
  '/accountant/cashbook': typeof AuthenticatedAccountantCashbookRoute
  '/accountant/invoices': typeof AuthenticatedAccountantInvoicesRoute
  '/accountant/payments': typeof AuthenticatedAccountantPaymentsRoute
  '/accountant/reconcile': typeof AuthenticatedAccountantReconcileRoute
  '/accountant/reports': typeof AuthenticatedAccountantReportsRoute
  '/accountant/vendor-payments': typeof AuthenticatedAccountantVendorPaymentsRoute
  '/admin/analysis': typeof AuthenticatedAdminAnalysisRoute
  '/admin/todos': typeof AuthenticatedAdminTodosRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/client/new': typeof AuthenticatedClientNewRoute
  '/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/project-viewer/$projectId': typeof AuthenticatedProjectViewerProjectIdRoute
  '/accountant': typeof AuthenticatedAccountantIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/engineer': typeof AuthenticatedEngineerIndexRoute
  '/project-viewer': typeof AuthenticatedProjectViewerIndexRoute
  '/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/analysis': typeof AuthenticatedMiniAdminAdminAnalysisRoute
  '/mini-admin/Admin/vendors': typeof AuthenticatedMiniAdminAdminVendorsRoute
  '/mini-admin/Engineer/$projectId': typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  '/mini-admin/Todo/todo': typeof AuthenticatedMiniAdminTodoTodoRoute
  '/mini-admin/Dashboard': typeof AuthenticatedMiniAdminDashboardIndexRoute
  '/mini-admin/Engineer': typeof AuthenticatedMiniAdminEngineerIndexRoute
  '/mini-admin/Admin/Clients/$projectId': typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  '/mini-admin/Admin/Clients/new': typeof AuthenticatedMiniAdminAdminClientsNewRoute
  '/mini-admin/Engineer/$projectId/compare': typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  '/mini-admin/Engineer/$projectId/inspection': typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  '/mini-admin/Engineer/$projectId/messages': typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  '/mini-admin/Engineer/$projectId/quotation': typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  '/mini-admin/Engineer/$projectId/worksheet': typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/Clients': typeof AuthenticatedMiniAdminAdminClientsIndexRoute
  '/mini-admin/Admin/ProjectViewers': typeof AuthenticatedMiniAdminAdminProjectViewersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/accountant': typeof AuthenticatedAccountantRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/engineer': typeof AuthenticatedEngineerRouteRouteWithChildren
  '/_authenticated/mini-admin': typeof AuthenticatedMiniAdminRouteRouteWithChildren
  '/_authenticated/project-viewer': typeof AuthenticatedProjectViewerRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/accountant/accounts': typeof AuthenticatedAccountantAccountsRoute
  '/_authenticated/accountant/analysis': typeof AuthenticatedAccountantAnalysisRoute
  '/_authenticated/accountant/bank-accounts': typeof AuthenticatedAccountantBankAccountsRoute
  '/_authenticated/accountant/bank-import': typeof AuthenticatedAccountantBankImportRoute
  '/_authenticated/accountant/bills': typeof AuthenticatedAccountantBillsRoute
  '/_authenticated/accountant/cashbook': typeof AuthenticatedAccountantCashbookRoute
  '/_authenticated/accountant/invoices': typeof AuthenticatedAccountantInvoicesRoute
  '/_authenticated/accountant/payments': typeof AuthenticatedAccountantPaymentsRoute
  '/_authenticated/accountant/reconcile': typeof AuthenticatedAccountantReconcileRoute
  '/_authenticated/accountant/reports': typeof AuthenticatedAccountantReportsRoute
  '/_authenticated/accountant/vendor-payments': typeof AuthenticatedAccountantVendorPaymentsRoute
  '/_authenticated/admin/analysis': typeof AuthenticatedAdminAnalysisRoute
  '/_authenticated/admin/todos': typeof AuthenticatedAdminTodosRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/_authenticated/client/new': typeof AuthenticatedClientNewRoute
  '/_authenticated/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/_authenticated/project-viewer/$projectId': typeof AuthenticatedProjectViewerProjectIdRoute
  '/_authenticated/accountant/': typeof AuthenticatedAccountantIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/engineer/': typeof AuthenticatedEngineerIndexRoute
  '/_authenticated/project-viewer/': typeof AuthenticatedProjectViewerIndexRoute
  '/_authenticated/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/_authenticated/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/_authenticated/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/_authenticated/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/_authenticated/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
  '/_authenticated/mini-admin/Admin/analysis': typeof AuthenticatedMiniAdminAdminAnalysisRoute
  '/_authenticated/mini-admin/Admin/vendors': typeof AuthenticatedMiniAdminAdminVendorsRoute
  '/_authenticated/mini-admin/Engineer/$projectId': typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  '/_authenticated/mini-admin/Todo/todo': typeof AuthenticatedMiniAdminTodoTodoRoute
  '/_authenticated/mini-admin/Dashboard/': typeof AuthenticatedMiniAdminDashboardIndexRoute
  '/_authenticated/mini-admin/Engineer/': typeof AuthenticatedMiniAdminEngineerIndexRoute
  '/_authenticated/mini-admin/Admin/Clients/$projectId': typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  '/_authenticated/mini-admin/Admin/Clients/new': typeof AuthenticatedMiniAdminAdminClientsNewRoute
  '/_authenticated/mini-admin/Engineer/$projectId/compare': typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  '/_authenticated/mini-admin/Engineer/$projectId/inspection': typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  '/_authenticated/mini-admin/Engineer/$projectId/messages': typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  '/_authenticated/mini-admin/Engineer/$projectId/quotation': typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  '/_authenticated/mini-admin/Engineer/$projectId/worksheet': typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
  '/_authenticated/mini-admin/Admin/Clients/': typeof AuthenticatedMiniAdminAdminClientsIndexRoute
  '/_authenticated/mini-admin/Admin/ProjectViewers/': typeof AuthenticatedMiniAdminAdminProjectViewersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/accountant'
    | '/admin'
    | '/client'
    | '/engineer'
    | '/mini-admin'
    | '/project-viewer'
    | '/dashboard'
    | '/accountant/accounts'
    | '/accountant/analysis'
    | '/accountant/bank-accounts'
    | '/accountant/bank-import'
    | '/accountant/bills'
    | '/accountant/cashbook'
    | '/accountant/invoices'
    | '/accountant/payments'
    | '/accountant/reconcile'
    | '/accountant/reports'
    | '/accountant/vendor-payments'
    | '/admin/analysis'
    | '/admin/todos'
    | '/admin/vendors'
    | '/client/$projectId'
    | '/client/new'
    | '/engineer/$projectId'
    | '/project-viewer/$projectId'
    | '/accountant/'
    | '/admin/'
    | '/client/'
    | '/engineer/'
    | '/project-viewer/'
    | '/engineer/$projectId/compare'
    | '/engineer/$projectId/inspection'
    | '/engineer/$projectId/messages'
    | '/engineer/$projectId/quotation'
    | '/engineer/$projectId/worksheet'
    | '/mini-admin/Admin/analysis'
    | '/mini-admin/Admin/vendors'
    | '/mini-admin/Engineer/$projectId'
    | '/mini-admin/Todo/todo'
    | '/mini-admin/Dashboard/'
    | '/mini-admin/Engineer/'
    | '/mini-admin/Admin/Clients/$projectId'
    | '/mini-admin/Admin/Clients/new'
    | '/mini-admin/Engineer/$projectId/compare'
    | '/mini-admin/Engineer/$projectId/inspection'
    | '/mini-admin/Engineer/$projectId/messages'
    | '/mini-admin/Engineer/$projectId/quotation'
    | '/mini-admin/Engineer/$projectId/worksheet'
    | '/mini-admin/Admin/Clients/'
    | '/mini-admin/Admin/ProjectViewers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/mini-admin'
    | '/dashboard'
    | '/accountant/accounts'
    | '/accountant/analysis'
    | '/accountant/bank-accounts'
    | '/accountant/bank-import'
    | '/accountant/bills'
    | '/accountant/cashbook'
    | '/accountant/invoices'
    | '/accountant/payments'
    | '/accountant/reconcile'
    | '/accountant/reports'
    | '/accountant/vendor-payments'
    | '/admin/analysis'
    | '/admin/todos'
    | '/admin/vendors'
    | '/client/$projectId'
    | '/client/new'
    | '/engineer/$projectId'
    | '/project-viewer/$projectId'
    | '/accountant'
    | '/admin'
    | '/client'
    | '/engineer'
    | '/project-viewer'
    | '/engineer/$projectId/compare'
    | '/engineer/$projectId/inspection'
    | '/engineer/$projectId/messages'
    | '/engineer/$projectId/quotation'
    | '/engineer/$projectId/worksheet'
    | '/mini-admin/Admin/analysis'
    | '/mini-admin/Admin/vendors'
    | '/mini-admin/Engineer/$projectId'
    | '/mini-admin/Todo/todo'
    | '/mini-admin/Dashboard'
    | '/mini-admin/Engineer'
    | '/mini-admin/Admin/Clients/$projectId'
    | '/mini-admin/Admin/Clients/new'
    | '/mini-admin/Engineer/$projectId/compare'
    | '/mini-admin/Engineer/$projectId/inspection'
    | '/mini-admin/Engineer/$projectId/messages'
    | '/mini-admin/Engineer/$projectId/quotation'
    | '/mini-admin/Engineer/$projectId/worksheet'
    | '/mini-admin/Admin/Clients'
    | '/mini-admin/Admin/ProjectViewers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/accountant'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/_authenticated/engineer'
    | '/_authenticated/mini-admin'
    | '/_authenticated/project-viewer'
    | '/_authenticated/dashboard'
    | '/_authenticated/accountant/accounts'
    | '/_authenticated/accountant/analysis'
    | '/_authenticated/accountant/bank-accounts'
    | '/_authenticated/accountant/bank-import'
    | '/_authenticated/accountant/bills'
    | '/_authenticated/accountant/cashbook'
    | '/_authenticated/accountant/invoices'
    | '/_authenticated/accountant/payments'
    | '/_authenticated/accountant/reconcile'
    | '/_authenticated/accountant/reports'
    | '/_authenticated/accountant/vendor-payments'
    | '/_authenticated/admin/analysis'
    | '/_authenticated/admin/todos'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/client/$projectId'
    | '/_authenticated/client/new'
    | '/_authenticated/engineer/$projectId'
    | '/_authenticated/project-viewer/$projectId'
    | '/_authenticated/accountant/'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/engineer/'
    | '/_authenticated/project-viewer/'
    | '/_authenticated/engineer/$projectId/compare'
    | '/_authenticated/engineer/$projectId/inspection'
    | '/_authenticated/engineer/$projectId/messages'
    | '/_authenticated/engineer/$projectId/quotation'
    | '/_authenticated/engineer/$projectId/worksheet'
    | '/_authenticated/mini-admin/Admin/analysis'
    | '/_authenticated/mini-admin/Admin/vendors'
    | '/_authenticated/mini-admin/Engineer/$projectId'
    | '/_authenticated/mini-admin/Todo/todo'
    | '/_authenticated/mini-admin/Dashboard/'
    | '/_authenticated/mini-admin/Engineer/'
    | '/_authenticated/mini-admin/Admin/Clients/$projectId'
    | '/_authenticated/mini-admin/Admin/Clients/new'
    | '/_authenticated/mini-admin/Engineer/$projectId/compare'
    | '/_authenticated/mini-admin/Engineer/$projectId/inspection'
    | '/_authenticated/mini-admin/Engineer/$projectId/messages'
    | '/_authenticated/mini-admin/Engineer/$projectId/quotation'
    | '/_authenticated/mini-admin/Engineer/$projectId/worksheet'
    | '/_authenticated/mini-admin/Admin/Clients/'
    | '/_authenticated/mini-admin/Admin/ProjectViewers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-viewer': {
      id: '/_authenticated/project-viewer'
      path: '/project-viewer'
      fullPath: '/project-viewer'
      preLoaderRoute: typeof AuthenticatedProjectViewerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mini-admin': {
      id: '/_authenticated/mini-admin'
      path: '/mini-admin'
      fullPath: '/mini-admin'
      preLoaderRoute: typeof AuthenticatedMiniAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer': {
      id: '/_authenticated/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AuthenticatedEngineerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accountant': {
      id: '/_authenticated/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AuthenticatedAccountantRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/project-viewer/': {
      id: '/_authenticated/project-viewer/'
      path: '/'
      fullPath: '/project-viewer/'
      preLoaderRoute: typeof AuthenticatedProjectViewerIndexRouteImport
      parentRoute: typeof AuthenticatedProjectViewerRouteRoute
    }
    '/_authenticated/engineer/': {
      id: '/_authenticated/engineer/'
      path: '/'
      fullPath: '/engineer/'
      preLoaderRoute: typeof AuthenticatedEngineerIndexRouteImport
      parentRoute: typeof AuthenticatedEngineerRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/accountant/': {
      id: '/_authenticated/accountant/'
      path: '/'
      fullPath: '/accountant/'
      preLoaderRoute: typeof AuthenticatedAccountantIndexRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/project-viewer/$projectId': {
      id: '/_authenticated/project-viewer/$projectId'
      path: '/$projectId'
      fullPath: '/project-viewer/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectViewerProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectViewerRouteRoute
    }
    '/_authenticated/engineer/$projectId': {
      id: '/_authenticated/engineer/$projectId'
      path: '/$projectId'
      fullPath: '/engineer/$projectId'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdRouteImport
      parentRoute: typeof AuthenticatedEngineerRouteRoute
    }
    '/_authenticated/client/new': {
      id: '/_authenticated/client/new'
      path: '/new'
      fullPath: '/client/new'
      preLoaderRoute: typeof AuthenticatedClientNewRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/client/$projectId': {
      id: '/_authenticated/client/$projectId'
      path: '/$projectId'
      fullPath: '/client/$projectId'
      preLoaderRoute: typeof AuthenticatedClientProjectIdRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/todos': {
      id: '/_authenticated/admin/todos'
      path: '/todos'
      fullPath: '/admin/todos'
      preLoaderRoute: typeof AuthenticatedAdminTodosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analysis': {
      id: '/_authenticated/admin/analysis'
      path: '/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof AuthenticatedAdminAnalysisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/accountant/vendor-payments': {
      id: '/_authenticated/accountant/vendor-payments'
      path: '/vendor-payments'
      fullPath: '/accountant/vendor-payments'
      preLoaderRoute: typeof AuthenticatedAccountantVendorPaymentsRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/reports': {
      id: '/_authenticated/accountant/reports'
      path: '/reports'
      fullPath: '/accountant/reports'
      preLoaderRoute: typeof AuthenticatedAccountantReportsRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/reconcile': {
      id: '/_authenticated/accountant/reconcile'
      path: '/reconcile'
      fullPath: '/accountant/reconcile'
      preLoaderRoute: typeof AuthenticatedAccountantReconcileRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/payments': {
      id: '/_authenticated/accountant/payments'
      path: '/payments'
      fullPath: '/accountant/payments'
      preLoaderRoute: typeof AuthenticatedAccountantPaymentsRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/invoices': {
      id: '/_authenticated/accountant/invoices'
      path: '/invoices'
      fullPath: '/accountant/invoices'
      preLoaderRoute: typeof AuthenticatedAccountantInvoicesRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/cashbook': {
      id: '/_authenticated/accountant/cashbook'
      path: '/cashbook'
      fullPath: '/accountant/cashbook'
      preLoaderRoute: typeof AuthenticatedAccountantCashbookRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/bills': {
      id: '/_authenticated/accountant/bills'
      path: '/bills'
      fullPath: '/accountant/bills'
      preLoaderRoute: typeof AuthenticatedAccountantBillsRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/bank-import': {
      id: '/_authenticated/accountant/bank-import'
      path: '/bank-import'
      fullPath: '/accountant/bank-import'
      preLoaderRoute: typeof AuthenticatedAccountantBankImportRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/bank-accounts': {
      id: '/_authenticated/accountant/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/accountant/bank-accounts'
      preLoaderRoute: typeof AuthenticatedAccountantBankAccountsRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/analysis': {
      id: '/_authenticated/accountant/analysis'
      path: '/analysis'
      fullPath: '/accountant/analysis'
      preLoaderRoute: typeof AuthenticatedAccountantAnalysisRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/accountant/accounts': {
      id: '/_authenticated/accountant/accounts'
      path: '/accounts'
      fullPath: '/accountant/accounts'
      preLoaderRoute: typeof AuthenticatedAccountantAccountsRouteImport
      parentRoute: typeof AuthenticatedAccountantRouteRoute
    }
    '/_authenticated/mini-admin/Engineer/': {
      id: '/_authenticated/mini-admin/Engineer/'
      path: '/Engineer'
      fullPath: '/mini-admin/Engineer/'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Dashboard/': {
      id: '/_authenticated/mini-admin/Dashboard/'
      path: '/Dashboard'
      fullPath: '/mini-admin/Dashboard/'
      preLoaderRoute: typeof AuthenticatedMiniAdminDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Todo/todo': {
      id: '/_authenticated/mini-admin/Todo/todo'
      path: '/Todo/todo'
      fullPath: '/mini-admin/Todo/todo'
      preLoaderRoute: typeof AuthenticatedMiniAdminTodoTodoRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId': {
      id: '/_authenticated/mini-admin/Engineer/$projectId'
      path: '/Engineer/$projectId'
      fullPath: '/mini-admin/Engineer/$projectId'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/vendors': {
      id: '/_authenticated/mini-admin/Admin/vendors'
      path: '/Admin/vendors'
      fullPath: '/mini-admin/Admin/vendors'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/analysis': {
      id: '/_authenticated/mini-admin/Admin/analysis'
      path: '/Admin/analysis'
      fullPath: '/mini-admin/Admin/analysis'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminAnalysisRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/engineer/$projectId/worksheet': {
      id: '/_authenticated/engineer/$projectId/worksheet'
      path: '/worksheet'
      fullPath: '/engineer/$projectId/worksheet'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdWorksheetRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/quotation': {
      id: '/_authenticated/engineer/$projectId/quotation'
      path: '/quotation'
      fullPath: '/engineer/$projectId/quotation'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdQuotationRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/messages': {
      id: '/_authenticated/engineer/$projectId/messages'
      path: '/messages'
      fullPath: '/engineer/$projectId/messages'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdMessagesRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/inspection': {
      id: '/_authenticated/engineer/$projectId/inspection'
      path: '/inspection'
      fullPath: '/engineer/$projectId/inspection'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdInspectionRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/compare': {
      id: '/_authenticated/engineer/$projectId/compare'
      path: '/compare'
      fullPath: '/engineer/$projectId/compare'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdCompareRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Admin/ProjectViewers/': {
      id: '/_authenticated/mini-admin/Admin/ProjectViewers/'
      path: '/Admin/ProjectViewers'
      fullPath: '/mini-admin/Admin/ProjectViewers/'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminProjectViewersIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/Clients/': {
      id: '/_authenticated/mini-admin/Admin/Clients/'
      path: '/Admin/Clients'
      fullPath: '/mini-admin/Admin/Clients/'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/worksheet': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/worksheet'
      path: '/worksheet'
      fullPath: '/mini-admin/Engineer/$projectId/worksheet'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/quotation': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/quotation'
      path: '/quotation'
      fullPath: '/mini-admin/Engineer/$projectId/quotation'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/messages': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/messages'
      path: '/messages'
      fullPath: '/mini-admin/Engineer/$projectId/messages'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/inspection': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/inspection'
      path: '/inspection'
      fullPath: '/mini-admin/Engineer/$projectId/inspection'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/compare': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/compare'
      path: '/compare'
      fullPath: '/mini-admin/Engineer/$projectId/compare'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdCompareRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Admin/Clients/new': {
      id: '/_authenticated/mini-admin/Admin/Clients/new'
      path: '/Admin/Clients/new'
      fullPath: '/mini-admin/Admin/Clients/new'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsNewRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/Clients/$projectId': {
      id: '/_authenticated/mini-admin/Admin/Clients/$projectId'
      path: '/Admin/Clients/$projectId'
      fullPath: '/mini-admin/Admin/Clients/$projectId'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsProjectIdRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
  }
}

interface AuthenticatedAccountantRouteRouteChildren {
  AuthenticatedAccountantAccountsRoute: typeof AuthenticatedAccountantAccountsRoute
  AuthenticatedAccountantAnalysisRoute: typeof AuthenticatedAccountantAnalysisRoute
  AuthenticatedAccountantBankAccountsRoute: typeof AuthenticatedAccountantBankAccountsRoute
  AuthenticatedAccountantBankImportRoute: typeof AuthenticatedAccountantBankImportRoute
  AuthenticatedAccountantBillsRoute: typeof AuthenticatedAccountantBillsRoute
  AuthenticatedAccountantCashbookRoute: typeof AuthenticatedAccountantCashbookRoute
  AuthenticatedAccountantInvoicesRoute: typeof AuthenticatedAccountantInvoicesRoute
  AuthenticatedAccountantPaymentsRoute: typeof AuthenticatedAccountantPaymentsRoute
  AuthenticatedAccountantReconcileRoute: typeof AuthenticatedAccountantReconcileRoute
  AuthenticatedAccountantReportsRoute: typeof AuthenticatedAccountantReportsRoute
  AuthenticatedAccountantVendorPaymentsRoute: typeof AuthenticatedAccountantVendorPaymentsRoute
  AuthenticatedAccountantIndexRoute: typeof AuthenticatedAccountantIndexRoute
}

const AuthenticatedAccountantRouteRouteChildren: AuthenticatedAccountantRouteRouteChildren =
  {
    AuthenticatedAccountantAccountsRoute: AuthenticatedAccountantAccountsRoute,
    AuthenticatedAccountantAnalysisRoute: AuthenticatedAccountantAnalysisRoute,
    AuthenticatedAccountantBankAccountsRoute:
      AuthenticatedAccountantBankAccountsRoute,
    AuthenticatedAccountantBankImportRoute:
      AuthenticatedAccountantBankImportRoute,
    AuthenticatedAccountantBillsRoute: AuthenticatedAccountantBillsRoute,
    AuthenticatedAccountantCashbookRoute: AuthenticatedAccountantCashbookRoute,
    AuthenticatedAccountantInvoicesRoute: AuthenticatedAccountantInvoicesRoute,
    AuthenticatedAccountantPaymentsRoute: AuthenticatedAccountantPaymentsRoute,
    AuthenticatedAccountantReconcileRoute:
      AuthenticatedAccountantReconcileRoute,
    AuthenticatedAccountantReportsRoute: AuthenticatedAccountantReportsRoute,
    AuthenticatedAccountantVendorPaymentsRoute:
      AuthenticatedAccountantVendorPaymentsRoute,
    AuthenticatedAccountantIndexRoute: AuthenticatedAccountantIndexRoute,
  }

const AuthenticatedAccountantRouteRouteWithChildren =
  AuthenticatedAccountantRouteRoute._addFileChildren(
    AuthenticatedAccountantRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalysisRoute: typeof AuthenticatedAdminAnalysisRoute
  AuthenticatedAdminTodosRoute: typeof AuthenticatedAdminTodosRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalysisRoute: AuthenticatedAdminAnalysisRoute,
    AuthenticatedAdminTodosRoute: AuthenticatedAdminTodosRoute,
    AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientProjectIdRoute: typeof AuthenticatedClientProjectIdRoute
  AuthenticatedClientNewRoute: typeof AuthenticatedClientNewRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientProjectIdRoute: AuthenticatedClientProjectIdRoute,
    AuthenticatedClientNewRoute: AuthenticatedClientNewRoute,
    AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedEngineerProjectIdRouteChildren {
  AuthenticatedEngineerProjectIdCompareRoute: typeof AuthenticatedEngineerProjectIdCompareRoute
  AuthenticatedEngineerProjectIdInspectionRoute: typeof AuthenticatedEngineerProjectIdInspectionRoute
  AuthenticatedEngineerProjectIdMessagesRoute: typeof AuthenticatedEngineerProjectIdMessagesRoute
  AuthenticatedEngineerProjectIdQuotationRoute: typeof AuthenticatedEngineerProjectIdQuotationRoute
  AuthenticatedEngineerProjectIdWorksheetRoute: typeof AuthenticatedEngineerProjectIdWorksheetRoute
}

const AuthenticatedEngineerProjectIdRouteChildren: AuthenticatedEngineerProjectIdRouteChildren =
  {
    AuthenticatedEngineerProjectIdCompareRoute:
      AuthenticatedEngineerProjectIdCompareRoute,
    AuthenticatedEngineerProjectIdInspectionRoute:
      AuthenticatedEngineerProjectIdInspectionRoute,
    AuthenticatedEngineerProjectIdMessagesRoute:
      AuthenticatedEngineerProjectIdMessagesRoute,
    AuthenticatedEngineerProjectIdQuotationRoute:
      AuthenticatedEngineerProjectIdQuotationRoute,
    AuthenticatedEngineerProjectIdWorksheetRoute:
      AuthenticatedEngineerProjectIdWorksheetRoute,
  }

const AuthenticatedEngineerProjectIdRouteWithChildren =
  AuthenticatedEngineerProjectIdRoute._addFileChildren(
    AuthenticatedEngineerProjectIdRouteChildren,
  )

interface AuthenticatedEngineerRouteRouteChildren {
  AuthenticatedEngineerProjectIdRoute: typeof AuthenticatedEngineerProjectIdRouteWithChildren
  AuthenticatedEngineerIndexRoute: typeof AuthenticatedEngineerIndexRoute
}

const AuthenticatedEngineerRouteRouteChildren: AuthenticatedEngineerRouteRouteChildren =
  {
    AuthenticatedEngineerProjectIdRoute:
      AuthenticatedEngineerProjectIdRouteWithChildren,
    AuthenticatedEngineerIndexRoute: AuthenticatedEngineerIndexRoute,
  }

const AuthenticatedEngineerRouteRouteWithChildren =
  AuthenticatedEngineerRouteRoute._addFileChildren(
    AuthenticatedEngineerRouteRouteChildren,
  )

interface AuthenticatedMiniAdminEngineerProjectIdRouteChildren {
  AuthenticatedMiniAdminEngineerProjectIdCompareRoute: typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  AuthenticatedMiniAdminEngineerProjectIdInspectionRoute: typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  AuthenticatedMiniAdminEngineerProjectIdMessagesRoute: typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  AuthenticatedMiniAdminEngineerProjectIdQuotationRoute: typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute: typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
}

const AuthenticatedMiniAdminEngineerProjectIdRouteChildren: AuthenticatedMiniAdminEngineerProjectIdRouteChildren =
  {
    AuthenticatedMiniAdminEngineerProjectIdCompareRoute:
      AuthenticatedMiniAdminEngineerProjectIdCompareRoute,
    AuthenticatedMiniAdminEngineerProjectIdInspectionRoute:
      AuthenticatedMiniAdminEngineerProjectIdInspectionRoute,
    AuthenticatedMiniAdminEngineerProjectIdMessagesRoute:
      AuthenticatedMiniAdminEngineerProjectIdMessagesRoute,
    AuthenticatedMiniAdminEngineerProjectIdQuotationRoute:
      AuthenticatedMiniAdminEngineerProjectIdQuotationRoute,
    AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute:
      AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute,
  }

const AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren =
  AuthenticatedMiniAdminEngineerProjectIdRoute._addFileChildren(
    AuthenticatedMiniAdminEngineerProjectIdRouteChildren,
  )

interface AuthenticatedMiniAdminRouteRouteChildren {
  AuthenticatedMiniAdminAdminAnalysisRoute: typeof AuthenticatedMiniAdminAdminAnalysisRoute
  AuthenticatedMiniAdminAdminVendorsRoute: typeof AuthenticatedMiniAdminAdminVendorsRoute
  AuthenticatedMiniAdminEngineerProjectIdRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  AuthenticatedMiniAdminTodoTodoRoute: typeof AuthenticatedMiniAdminTodoTodoRoute
  AuthenticatedMiniAdminDashboardIndexRoute: typeof AuthenticatedMiniAdminDashboardIndexRoute
  AuthenticatedMiniAdminEngineerIndexRoute: typeof AuthenticatedMiniAdminEngineerIndexRoute
  AuthenticatedMiniAdminAdminClientsProjectIdRoute: typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  AuthenticatedMiniAdminAdminClientsNewRoute: typeof AuthenticatedMiniAdminAdminClientsNewRoute
  AuthenticatedMiniAdminAdminClientsIndexRoute: typeof AuthenticatedMiniAdminAdminClientsIndexRoute
  AuthenticatedMiniAdminAdminProjectViewersIndexRoute: typeof AuthenticatedMiniAdminAdminProjectViewersIndexRoute
}

const AuthenticatedMiniAdminRouteRouteChildren: AuthenticatedMiniAdminRouteRouteChildren =
  {
    AuthenticatedMiniAdminAdminAnalysisRoute:
      AuthenticatedMiniAdminAdminAnalysisRoute,
    AuthenticatedMiniAdminAdminVendorsRoute:
      AuthenticatedMiniAdminAdminVendorsRoute,
    AuthenticatedMiniAdminEngineerProjectIdRoute:
      AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren,
    AuthenticatedMiniAdminTodoTodoRoute: AuthenticatedMiniAdminTodoTodoRoute,
    AuthenticatedMiniAdminDashboardIndexRoute:
      AuthenticatedMiniAdminDashboardIndexRoute,
    AuthenticatedMiniAdminEngineerIndexRoute:
      AuthenticatedMiniAdminEngineerIndexRoute,
    AuthenticatedMiniAdminAdminClientsProjectIdRoute:
      AuthenticatedMiniAdminAdminClientsProjectIdRoute,
    AuthenticatedMiniAdminAdminClientsNewRoute:
      AuthenticatedMiniAdminAdminClientsNewRoute,
    AuthenticatedMiniAdminAdminClientsIndexRoute:
      AuthenticatedMiniAdminAdminClientsIndexRoute,
    AuthenticatedMiniAdminAdminProjectViewersIndexRoute:
      AuthenticatedMiniAdminAdminProjectViewersIndexRoute,
  }

const AuthenticatedMiniAdminRouteRouteWithChildren =
  AuthenticatedMiniAdminRouteRoute._addFileChildren(
    AuthenticatedMiniAdminRouteRouteChildren,
  )

interface AuthenticatedProjectViewerRouteRouteChildren {
  AuthenticatedProjectViewerProjectIdRoute: typeof AuthenticatedProjectViewerProjectIdRoute
  AuthenticatedProjectViewerIndexRoute: typeof AuthenticatedProjectViewerIndexRoute
}

const AuthenticatedProjectViewerRouteRouteChildren: AuthenticatedProjectViewerRouteRouteChildren =
  {
    AuthenticatedProjectViewerProjectIdRoute:
      AuthenticatedProjectViewerProjectIdRoute,
    AuthenticatedProjectViewerIndexRoute: AuthenticatedProjectViewerIndexRoute,
  }

const AuthenticatedProjectViewerRouteRouteWithChildren =
  AuthenticatedProjectViewerRouteRoute._addFileChildren(
    AuthenticatedProjectViewerRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountantRouteRoute: typeof AuthenticatedAccountantRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedEngineerRouteRoute: typeof AuthenticatedEngineerRouteRouteWithChildren
  AuthenticatedMiniAdminRouteRoute: typeof AuthenticatedMiniAdminRouteRouteWithChildren
  AuthenticatedProjectViewerRouteRoute: typeof AuthenticatedProjectViewerRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountantRouteRoute:
    AuthenticatedAccountantRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedEngineerRouteRoute: AuthenticatedEngineerRouteRouteWithChildren,
  AuthenticatedMiniAdminRouteRoute:
    AuthenticatedMiniAdminRouteRouteWithChildren,
  AuthenticatedProjectViewerRouteRoute:
    AuthenticatedProjectViewerRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
