/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMiniAdminRouteRouteImport } from './routes/_authenticated/mini-admin/route'
import { Route as AuthenticatedMiniAdminIndexRouteImport } from './routes/_authenticated/mini-admin/index'
import { Route as AuthenticatedEngineerIndexRouteImport } from './routes/_authenticated/engineer/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedEngineerProjectIdRouteImport } from './routes/_authenticated/engineer/$projectId'
import { Route as AuthenticatedClientNewRouteImport } from './routes/_authenticated/client/new'
import { Route as AuthenticatedClientProjectIdRouteImport } from './routes/_authenticated/client/$projectId'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin/vendors'
import { Route as AuthenticatedAdminTodosRouteImport } from './routes/_authenticated/admin/todos'
import { Route as AuthenticatedAdminAnalysisRouteImport } from './routes/_authenticated/admin/analysis'
import { Route as AuthenticatedMiniAdminEngineerIndexRouteImport } from './routes/_authenticated/mini-admin/Engineer/index'
import { Route as AuthenticatedMiniAdminTodoTodoRouteImport } from './routes/_authenticated/mini-admin/Todo/todo'
import { Route as AuthenticatedMiniAdminEngineerProjectIdRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId'
import { Route as AuthenticatedMiniAdminAdminVendorsRouteImport } from './routes/_authenticated/mini-admin/Admin/vendors'
import { Route as AuthenticatedMiniAdminAdminClientsRouteImport } from './routes/_authenticated/mini-admin/Admin/clients'
import { Route as AuthenticatedMiniAdminAdminAnalysisRouteImport } from './routes/_authenticated/mini-admin/Admin/analysis'
import { Route as AuthenticatedEngineerProjectIdWorksheetRouteImport } from './routes/_authenticated/engineer/$projectId.worksheet'
import { Route as AuthenticatedEngineerProjectIdQuotationRouteImport } from './routes/_authenticated/engineer/$projectId.quotation'
import { Route as AuthenticatedEngineerProjectIdMessagesRouteImport } from './routes/_authenticated/engineer/$projectId.messages'
import { Route as AuthenticatedEngineerProjectIdInspectionRouteImport } from './routes/_authenticated/engineer/$projectId.inspection'
import { Route as AuthenticatedEngineerProjectIdCompareRouteImport } from './routes/_authenticated/engineer/$projectId.compare'
import { Route as AuthenticatedMiniAdminAdminClientsIndexRouteImport } from './routes/_authenticated/mini-admin/Admin/Clients/index'
import { Route as AuthenticatedMiniAdminEngineerProjectIdWorksheetRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.worksheet'
import { Route as AuthenticatedMiniAdminEngineerProjectIdQuotationRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.quotation'
import { Route as AuthenticatedMiniAdminEngineerProjectIdMessagesRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.messages'
import { Route as AuthenticatedMiniAdminEngineerProjectIdInspectionRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.inspection'
import { Route as AuthenticatedMiniAdminEngineerProjectIdCompareRouteImport } from './routes/_authenticated/mini-admin/Engineer/$projectId.compare'
import { Route as AuthenticatedMiniAdminAdminClientsNewRouteImport } from './routes/_authenticated/mini-admin/Admin/Clients/new'
import { Route as AuthenticatedMiniAdminAdminClientsProjectIdRouteImport } from './routes/_authenticated/mini-admin/Admin/Clients/$projectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiniAdminRouteRoute =
  AuthenticatedMiniAdminRouteRouteImport.update({
    id: '/mini-admin',
    path: '/mini-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiniAdminIndexRoute =
  AuthenticatedMiniAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedEngineerIndexRoute =
  AuthenticatedEngineerIndexRouteImport.update({
    id: '/engineer/',
    path: '/engineer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineerProjectIdRoute =
  AuthenticatedEngineerProjectIdRouteImport.update({
    id: '/engineer/$projectId',
    path: '/engineer/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientNewRoute = AuthenticatedClientNewRouteImport.update({
  id: '/client/new',
  path: '/client/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientProjectIdRoute =
  AuthenticatedClientProjectIdRouteImport.update({
    id: '/client/$projectId',
    path: '/client/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/admin/vendors',
    path: '/admin/vendors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTodosRoute = AuthenticatedAdminTodosRouteImport.update({
  id: '/admin/todos',
  path: '/admin/todos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalysisRoute =
  AuthenticatedAdminAnalysisRouteImport.update({
    id: '/admin/analysis',
    path: '/admin/analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiniAdminEngineerIndexRoute =
  AuthenticatedMiniAdminEngineerIndexRouteImport.update({
    id: '/Engineer/',
    path: '/Engineer/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminTodoTodoRoute =
  AuthenticatedMiniAdminTodoTodoRouteImport.update({
    id: '/Todo/todo',
    path: '/Todo/todo',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdRoute =
  AuthenticatedMiniAdminEngineerProjectIdRouteImport.update({
    id: '/Engineer/$projectId',
    path: '/Engineer/$projectId',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminVendorsRoute =
  AuthenticatedMiniAdminAdminVendorsRouteImport.update({
    id: '/Admin/vendors',
    path: '/Admin/vendors',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsRoute =
  AuthenticatedMiniAdminAdminClientsRouteImport.update({
    id: '/Admin/clients',
    path: '/Admin/clients',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminAnalysisRoute =
  AuthenticatedMiniAdminAdminAnalysisRouteImport.update({
    id: '/Admin/analysis',
    path: '/Admin/analysis',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedEngineerProjectIdWorksheetRoute =
  AuthenticatedEngineerProjectIdWorksheetRouteImport.update({
    id: '/worksheet',
    path: '/worksheet',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdQuotationRoute =
  AuthenticatedEngineerProjectIdQuotationRouteImport.update({
    id: '/quotation',
    path: '/quotation',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdMessagesRoute =
  AuthenticatedEngineerProjectIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdInspectionRoute =
  AuthenticatedEngineerProjectIdInspectionRouteImport.update({
    id: '/inspection',
    path: '/inspection',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedEngineerProjectIdCompareRoute =
  AuthenticatedEngineerProjectIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsIndexRoute =
  AuthenticatedMiniAdminAdminClientsIndexRouteImport.update({
    id: '/Admin/Clients/',
    path: '/Admin/Clients/',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute =
  AuthenticatedMiniAdminEngineerProjectIdWorksheetRouteImport.update({
    id: '/worksheet',
    path: '/worksheet',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdQuotationRoute =
  AuthenticatedMiniAdminEngineerProjectIdQuotationRouteImport.update({
    id: '/quotation',
    path: '/quotation',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdMessagesRoute =
  AuthenticatedMiniAdminEngineerProjectIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdInspectionRoute =
  AuthenticatedMiniAdminEngineerProjectIdInspectionRouteImport.update({
    id: '/inspection',
    path: '/inspection',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminEngineerProjectIdCompareRoute =
  AuthenticatedMiniAdminEngineerProjectIdCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedMiniAdminEngineerProjectIdRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsNewRoute =
  AuthenticatedMiniAdminAdminClientsNewRouteImport.update({
    id: '/Admin/Clients/new',
    path: '/Admin/Clients/new',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)
const AuthenticatedMiniAdminAdminClientsProjectIdRoute =
  AuthenticatedMiniAdminAdminClientsProjectIdRouteImport.update({
    id: '/Admin/Clients/$projectId',
    path: '/Admin/Clients/$projectId',
    getParentRoute: () => AuthenticatedMiniAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mini-admin': typeof AuthenticatedMiniAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analysis': typeof AuthenticatedAdminAnalysisRoute
  '/admin/todos': typeof AuthenticatedAdminTodosRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/client/new': typeof AuthenticatedClientNewRoute
  '/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/engineer/': typeof AuthenticatedEngineerIndexRoute
  '/mini-admin/': typeof AuthenticatedMiniAdminIndexRoute
  '/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/analysis': typeof AuthenticatedMiniAdminAdminAnalysisRoute
  '/mini-admin/Admin/clients': typeof AuthenticatedMiniAdminAdminClientsRoute
  '/mini-admin/Admin/vendors': typeof AuthenticatedMiniAdminAdminVendorsRoute
  '/mini-admin/Engineer/$projectId': typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  '/mini-admin/Todo/todo': typeof AuthenticatedMiniAdminTodoTodoRoute
  '/mini-admin/Engineer/': typeof AuthenticatedMiniAdminEngineerIndexRoute
  '/mini-admin/Admin/Clients/$projectId': typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  '/mini-admin/Admin/Clients/new': typeof AuthenticatedMiniAdminAdminClientsNewRoute
  '/mini-admin/Engineer/$projectId/compare': typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  '/mini-admin/Engineer/$projectId/inspection': typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  '/mini-admin/Engineer/$projectId/messages': typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  '/mini-admin/Engineer/$projectId/quotation': typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  '/mini-admin/Engineer/$projectId/worksheet': typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/Clients/': typeof AuthenticatedMiniAdminAdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analysis': typeof AuthenticatedAdminAnalysisRoute
  '/admin/todos': typeof AuthenticatedAdminTodosRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/client/new': typeof AuthenticatedClientNewRoute
  '/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/engineer': typeof AuthenticatedEngineerIndexRoute
  '/mini-admin': typeof AuthenticatedMiniAdminIndexRoute
  '/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/analysis': typeof AuthenticatedMiniAdminAdminAnalysisRoute
  '/mini-admin/Admin/clients': typeof AuthenticatedMiniAdminAdminClientsRoute
  '/mini-admin/Admin/vendors': typeof AuthenticatedMiniAdminAdminVendorsRoute
  '/mini-admin/Engineer/$projectId': typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  '/mini-admin/Todo/todo': typeof AuthenticatedMiniAdminTodoTodoRoute
  '/mini-admin/Engineer': typeof AuthenticatedMiniAdminEngineerIndexRoute
  '/mini-admin/Admin/Clients/$projectId': typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  '/mini-admin/Admin/Clients/new': typeof AuthenticatedMiniAdminAdminClientsNewRoute
  '/mini-admin/Engineer/$projectId/compare': typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  '/mini-admin/Engineer/$projectId/inspection': typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  '/mini-admin/Engineer/$projectId/messages': typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  '/mini-admin/Engineer/$projectId/quotation': typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  '/mini-admin/Engineer/$projectId/worksheet': typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
  '/mini-admin/Admin/Clients': typeof AuthenticatedMiniAdminAdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/mini-admin': typeof AuthenticatedMiniAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/analysis': typeof AuthenticatedAdminAnalysisRoute
  '/_authenticated/admin/todos': typeof AuthenticatedAdminTodosRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/client/$projectId': typeof AuthenticatedClientProjectIdRoute
  '/_authenticated/client/new': typeof AuthenticatedClientNewRoute
  '/_authenticated/engineer/$projectId': typeof AuthenticatedEngineerProjectIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/engineer/': typeof AuthenticatedEngineerIndexRoute
  '/_authenticated/mini-admin/': typeof AuthenticatedMiniAdminIndexRoute
  '/_authenticated/engineer/$projectId/compare': typeof AuthenticatedEngineerProjectIdCompareRoute
  '/_authenticated/engineer/$projectId/inspection': typeof AuthenticatedEngineerProjectIdInspectionRoute
  '/_authenticated/engineer/$projectId/messages': typeof AuthenticatedEngineerProjectIdMessagesRoute
  '/_authenticated/engineer/$projectId/quotation': typeof AuthenticatedEngineerProjectIdQuotationRoute
  '/_authenticated/engineer/$projectId/worksheet': typeof AuthenticatedEngineerProjectIdWorksheetRoute
  '/_authenticated/mini-admin/Admin/analysis': typeof AuthenticatedMiniAdminAdminAnalysisRoute
  '/_authenticated/mini-admin/Admin/clients': typeof AuthenticatedMiniAdminAdminClientsRoute
  '/_authenticated/mini-admin/Admin/vendors': typeof AuthenticatedMiniAdminAdminVendorsRoute
  '/_authenticated/mini-admin/Engineer/$projectId': typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  '/_authenticated/mini-admin/Todo/todo': typeof AuthenticatedMiniAdminTodoTodoRoute
  '/_authenticated/mini-admin/Engineer/': typeof AuthenticatedMiniAdminEngineerIndexRoute
  '/_authenticated/mini-admin/Admin/Clients/$projectId': typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  '/_authenticated/mini-admin/Admin/Clients/new': typeof AuthenticatedMiniAdminAdminClientsNewRoute
  '/_authenticated/mini-admin/Engineer/$projectId/compare': typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  '/_authenticated/mini-admin/Engineer/$projectId/inspection': typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  '/_authenticated/mini-admin/Engineer/$projectId/messages': typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  '/_authenticated/mini-admin/Engineer/$projectId/quotation': typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  '/_authenticated/mini-admin/Engineer/$projectId/worksheet': typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
  '/_authenticated/mini-admin/Admin/Clients/': typeof AuthenticatedMiniAdminAdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mini-admin'
    | '/dashboard'
    | '/admin/analysis'
    | '/admin/todos'
    | '/admin/vendors'
    | '/client/$projectId'
    | '/client/new'
    | '/engineer/$projectId'
    | '/admin/'
    | '/client/'
    | '/engineer/'
    | '/mini-admin/'
    | '/engineer/$projectId/compare'
    | '/engineer/$projectId/inspection'
    | '/engineer/$projectId/messages'
    | '/engineer/$projectId/quotation'
    | '/engineer/$projectId/worksheet'
    | '/mini-admin/Admin/analysis'
    | '/mini-admin/Admin/clients'
    | '/mini-admin/Admin/vendors'
    | '/mini-admin/Engineer/$projectId'
    | '/mini-admin/Todo/todo'
    | '/mini-admin/Engineer/'
    | '/mini-admin/Admin/Clients/$projectId'
    | '/mini-admin/Admin/Clients/new'
    | '/mini-admin/Engineer/$projectId/compare'
    | '/mini-admin/Engineer/$projectId/inspection'
    | '/mini-admin/Engineer/$projectId/messages'
    | '/mini-admin/Engineer/$projectId/quotation'
    | '/mini-admin/Engineer/$projectId/worksheet'
    | '/mini-admin/Admin/Clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/analysis'
    | '/admin/todos'
    | '/admin/vendors'
    | '/client/$projectId'
    | '/client/new'
    | '/engineer/$projectId'
    | '/admin'
    | '/client'
    | '/engineer'
    | '/mini-admin'
    | '/engineer/$projectId/compare'
    | '/engineer/$projectId/inspection'
    | '/engineer/$projectId/messages'
    | '/engineer/$projectId/quotation'
    | '/engineer/$projectId/worksheet'
    | '/mini-admin/Admin/analysis'
    | '/mini-admin/Admin/clients'
    | '/mini-admin/Admin/vendors'
    | '/mini-admin/Engineer/$projectId'
    | '/mini-admin/Todo/todo'
    | '/mini-admin/Engineer'
    | '/mini-admin/Admin/Clients/$projectId'
    | '/mini-admin/Admin/Clients/new'
    | '/mini-admin/Engineer/$projectId/compare'
    | '/mini-admin/Engineer/$projectId/inspection'
    | '/mini-admin/Engineer/$projectId/messages'
    | '/mini-admin/Engineer/$projectId/quotation'
    | '/mini-admin/Engineer/$projectId/worksheet'
    | '/mini-admin/Admin/Clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/mini-admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/analysis'
    | '/_authenticated/admin/todos'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/client/$projectId'
    | '/_authenticated/client/new'
    | '/_authenticated/engineer/$projectId'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/engineer/'
    | '/_authenticated/mini-admin/'
    | '/_authenticated/engineer/$projectId/compare'
    | '/_authenticated/engineer/$projectId/inspection'
    | '/_authenticated/engineer/$projectId/messages'
    | '/_authenticated/engineer/$projectId/quotation'
    | '/_authenticated/engineer/$projectId/worksheet'
    | '/_authenticated/mini-admin/Admin/analysis'
    | '/_authenticated/mini-admin/Admin/clients'
    | '/_authenticated/mini-admin/Admin/vendors'
    | '/_authenticated/mini-admin/Engineer/$projectId'
    | '/_authenticated/mini-admin/Todo/todo'
    | '/_authenticated/mini-admin/Engineer/'
    | '/_authenticated/mini-admin/Admin/Clients/$projectId'
    | '/_authenticated/mini-admin/Admin/Clients/new'
    | '/_authenticated/mini-admin/Engineer/$projectId/compare'
    | '/_authenticated/mini-admin/Engineer/$projectId/inspection'
    | '/_authenticated/mini-admin/Engineer/$projectId/messages'
    | '/_authenticated/mini-admin/Engineer/$projectId/quotation'
    | '/_authenticated/mini-admin/Engineer/$projectId/worksheet'
    | '/_authenticated/mini-admin/Admin/Clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mini-admin': {
      id: '/_authenticated/mini-admin'
      path: '/mini-admin'
      fullPath: '/mini-admin'
      preLoaderRoute: typeof AuthenticatedMiniAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mini-admin/': {
      id: '/_authenticated/mini-admin/'
      path: '/'
      fullPath: '/mini-admin/'
      preLoaderRoute: typeof AuthenticatedMiniAdminIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/engineer/': {
      id: '/_authenticated/engineer/'
      path: '/engineer'
      fullPath: '/engineer/'
      preLoaderRoute: typeof AuthenticatedEngineerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer/$projectId': {
      id: '/_authenticated/engineer/$projectId'
      path: '/engineer/$projectId'
      fullPath: '/engineer/$projectId'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/new': {
      id: '/_authenticated/client/new'
      path: '/client/new'
      fullPath: '/client/new'
      preLoaderRoute: typeof AuthenticatedClientNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/$projectId': {
      id: '/_authenticated/client/$projectId'
      path: '/client/$projectId'
      fullPath: '/client/$projectId'
      preLoaderRoute: typeof AuthenticatedClientProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/todos': {
      id: '/_authenticated/admin/todos'
      path: '/admin/todos'
      fullPath: '/admin/todos'
      preLoaderRoute: typeof AuthenticatedAdminTodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analysis': {
      id: '/_authenticated/admin/analysis'
      path: '/admin/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof AuthenticatedAdminAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mini-admin/Engineer/': {
      id: '/_authenticated/mini-admin/Engineer/'
      path: '/Engineer'
      fullPath: '/mini-admin/Engineer/'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Todo/todo': {
      id: '/_authenticated/mini-admin/Todo/todo'
      path: '/Todo/todo'
      fullPath: '/mini-admin/Todo/todo'
      preLoaderRoute: typeof AuthenticatedMiniAdminTodoTodoRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId': {
      id: '/_authenticated/mini-admin/Engineer/$projectId'
      path: '/Engineer/$projectId'
      fullPath: '/mini-admin/Engineer/$projectId'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/vendors': {
      id: '/_authenticated/mini-admin/Admin/vendors'
      path: '/Admin/vendors'
      fullPath: '/mini-admin/Admin/vendors'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/clients': {
      id: '/_authenticated/mini-admin/Admin/clients'
      path: '/Admin/clients'
      fullPath: '/mini-admin/Admin/clients'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/analysis': {
      id: '/_authenticated/mini-admin/Admin/analysis'
      path: '/Admin/analysis'
      fullPath: '/mini-admin/Admin/analysis'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminAnalysisRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/engineer/$projectId/worksheet': {
      id: '/_authenticated/engineer/$projectId/worksheet'
      path: '/worksheet'
      fullPath: '/engineer/$projectId/worksheet'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdWorksheetRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/quotation': {
      id: '/_authenticated/engineer/$projectId/quotation'
      path: '/quotation'
      fullPath: '/engineer/$projectId/quotation'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdQuotationRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/messages': {
      id: '/_authenticated/engineer/$projectId/messages'
      path: '/messages'
      fullPath: '/engineer/$projectId/messages'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdMessagesRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/inspection': {
      id: '/_authenticated/engineer/$projectId/inspection'
      path: '/inspection'
      fullPath: '/engineer/$projectId/inspection'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdInspectionRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/engineer/$projectId/compare': {
      id: '/_authenticated/engineer/$projectId/compare'
      path: '/compare'
      fullPath: '/engineer/$projectId/compare'
      preLoaderRoute: typeof AuthenticatedEngineerProjectIdCompareRouteImport
      parentRoute: typeof AuthenticatedEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Admin/Clients/': {
      id: '/_authenticated/mini-admin/Admin/Clients/'
      path: '/Admin/Clients'
      fullPath: '/mini-admin/Admin/Clients/'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/worksheet': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/worksheet'
      path: '/worksheet'
      fullPath: '/mini-admin/Engineer/$projectId/worksheet'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/quotation': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/quotation'
      path: '/quotation'
      fullPath: '/mini-admin/Engineer/$projectId/quotation'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/messages': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/messages'
      path: '/messages'
      fullPath: '/mini-admin/Engineer/$projectId/messages'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/inspection': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/inspection'
      path: '/inspection'
      fullPath: '/mini-admin/Engineer/$projectId/inspection'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Engineer/$projectId/compare': {
      id: '/_authenticated/mini-admin/Engineer/$projectId/compare'
      path: '/compare'
      fullPath: '/mini-admin/Engineer/$projectId/compare'
      preLoaderRoute: typeof AuthenticatedMiniAdminEngineerProjectIdCompareRouteImport
      parentRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRoute
    }
    '/_authenticated/mini-admin/Admin/Clients/new': {
      id: '/_authenticated/mini-admin/Admin/Clients/new'
      path: '/Admin/Clients/new'
      fullPath: '/mini-admin/Admin/Clients/new'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsNewRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
    '/_authenticated/mini-admin/Admin/Clients/$projectId': {
      id: '/_authenticated/mini-admin/Admin/Clients/$projectId'
      path: '/Admin/Clients/$projectId'
      fullPath: '/mini-admin/Admin/Clients/$projectId'
      preLoaderRoute: typeof AuthenticatedMiniAdminAdminClientsProjectIdRouteImport
      parentRoute: typeof AuthenticatedMiniAdminRouteRoute
    }
  }
}

interface AuthenticatedMiniAdminEngineerProjectIdRouteChildren {
  AuthenticatedMiniAdminEngineerProjectIdCompareRoute: typeof AuthenticatedMiniAdminEngineerProjectIdCompareRoute
  AuthenticatedMiniAdminEngineerProjectIdInspectionRoute: typeof AuthenticatedMiniAdminEngineerProjectIdInspectionRoute
  AuthenticatedMiniAdminEngineerProjectIdMessagesRoute: typeof AuthenticatedMiniAdminEngineerProjectIdMessagesRoute
  AuthenticatedMiniAdminEngineerProjectIdQuotationRoute: typeof AuthenticatedMiniAdminEngineerProjectIdQuotationRoute
  AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute: typeof AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute
}

const AuthenticatedMiniAdminEngineerProjectIdRouteChildren: AuthenticatedMiniAdminEngineerProjectIdRouteChildren =
  {
    AuthenticatedMiniAdminEngineerProjectIdCompareRoute:
      AuthenticatedMiniAdminEngineerProjectIdCompareRoute,
    AuthenticatedMiniAdminEngineerProjectIdInspectionRoute:
      AuthenticatedMiniAdminEngineerProjectIdInspectionRoute,
    AuthenticatedMiniAdminEngineerProjectIdMessagesRoute:
      AuthenticatedMiniAdminEngineerProjectIdMessagesRoute,
    AuthenticatedMiniAdminEngineerProjectIdQuotationRoute:
      AuthenticatedMiniAdminEngineerProjectIdQuotationRoute,
    AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute:
      AuthenticatedMiniAdminEngineerProjectIdWorksheetRoute,
  }

const AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren =
  AuthenticatedMiniAdminEngineerProjectIdRoute._addFileChildren(
    AuthenticatedMiniAdminEngineerProjectIdRouteChildren,
  )

interface AuthenticatedMiniAdminRouteRouteChildren {
  AuthenticatedMiniAdminIndexRoute: typeof AuthenticatedMiniAdminIndexRoute
  AuthenticatedMiniAdminAdminAnalysisRoute: typeof AuthenticatedMiniAdminAdminAnalysisRoute
  AuthenticatedMiniAdminAdminClientsRoute: typeof AuthenticatedMiniAdminAdminClientsRoute
  AuthenticatedMiniAdminAdminVendorsRoute: typeof AuthenticatedMiniAdminAdminVendorsRoute
  AuthenticatedMiniAdminEngineerProjectIdRoute: typeof AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren
  AuthenticatedMiniAdminTodoTodoRoute: typeof AuthenticatedMiniAdminTodoTodoRoute
  AuthenticatedMiniAdminEngineerIndexRoute: typeof AuthenticatedMiniAdminEngineerIndexRoute
  AuthenticatedMiniAdminAdminClientsProjectIdRoute: typeof AuthenticatedMiniAdminAdminClientsProjectIdRoute
  AuthenticatedMiniAdminAdminClientsNewRoute: typeof AuthenticatedMiniAdminAdminClientsNewRoute
  AuthenticatedMiniAdminAdminClientsIndexRoute: typeof AuthenticatedMiniAdminAdminClientsIndexRoute
}

const AuthenticatedMiniAdminRouteRouteChildren: AuthenticatedMiniAdminRouteRouteChildren =
  {
    AuthenticatedMiniAdminIndexRoute: AuthenticatedMiniAdminIndexRoute,
    AuthenticatedMiniAdminAdminAnalysisRoute:
      AuthenticatedMiniAdminAdminAnalysisRoute,
    AuthenticatedMiniAdminAdminClientsRoute:
      AuthenticatedMiniAdminAdminClientsRoute,
    AuthenticatedMiniAdminAdminVendorsRoute:
      AuthenticatedMiniAdminAdminVendorsRoute,
    AuthenticatedMiniAdminEngineerProjectIdRoute:
      AuthenticatedMiniAdminEngineerProjectIdRouteWithChildren,
    AuthenticatedMiniAdminTodoTodoRoute: AuthenticatedMiniAdminTodoTodoRoute,
    AuthenticatedMiniAdminEngineerIndexRoute:
      AuthenticatedMiniAdminEngineerIndexRoute,
    AuthenticatedMiniAdminAdminClientsProjectIdRoute:
      AuthenticatedMiniAdminAdminClientsProjectIdRoute,
    AuthenticatedMiniAdminAdminClientsNewRoute:
      AuthenticatedMiniAdminAdminClientsNewRoute,
    AuthenticatedMiniAdminAdminClientsIndexRoute:
      AuthenticatedMiniAdminAdminClientsIndexRoute,
  }

const AuthenticatedMiniAdminRouteRouteWithChildren =
  AuthenticatedMiniAdminRouteRoute._addFileChildren(
    AuthenticatedMiniAdminRouteRouteChildren,
  )

interface AuthenticatedEngineerProjectIdRouteChildren {
  AuthenticatedEngineerProjectIdCompareRoute: typeof AuthenticatedEngineerProjectIdCompareRoute
  AuthenticatedEngineerProjectIdInspectionRoute: typeof AuthenticatedEngineerProjectIdInspectionRoute
  AuthenticatedEngineerProjectIdMessagesRoute: typeof AuthenticatedEngineerProjectIdMessagesRoute
  AuthenticatedEngineerProjectIdQuotationRoute: typeof AuthenticatedEngineerProjectIdQuotationRoute
  AuthenticatedEngineerProjectIdWorksheetRoute: typeof AuthenticatedEngineerProjectIdWorksheetRoute
}

const AuthenticatedEngineerProjectIdRouteChildren: AuthenticatedEngineerProjectIdRouteChildren =
  {
    AuthenticatedEngineerProjectIdCompareRoute:
      AuthenticatedEngineerProjectIdCompareRoute,
    AuthenticatedEngineerProjectIdInspectionRoute:
      AuthenticatedEngineerProjectIdInspectionRoute,
    AuthenticatedEngineerProjectIdMessagesRoute:
      AuthenticatedEngineerProjectIdMessagesRoute,
    AuthenticatedEngineerProjectIdQuotationRoute:
      AuthenticatedEngineerProjectIdQuotationRoute,
    AuthenticatedEngineerProjectIdWorksheetRoute:
      AuthenticatedEngineerProjectIdWorksheetRoute,
  }

const AuthenticatedEngineerProjectIdRouteWithChildren =
  AuthenticatedEngineerProjectIdRoute._addFileChildren(
    AuthenticatedEngineerProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMiniAdminRouteRoute: typeof AuthenticatedMiniAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAnalysisRoute: typeof AuthenticatedAdminAnalysisRoute
  AuthenticatedAdminTodosRoute: typeof AuthenticatedAdminTodosRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedClientProjectIdRoute: typeof AuthenticatedClientProjectIdRoute
  AuthenticatedClientNewRoute: typeof AuthenticatedClientNewRoute
  AuthenticatedEngineerProjectIdRoute: typeof AuthenticatedEngineerProjectIdRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
  AuthenticatedEngineerIndexRoute: typeof AuthenticatedEngineerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMiniAdminRouteRoute:
    AuthenticatedMiniAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAnalysisRoute: AuthenticatedAdminAnalysisRoute,
  AuthenticatedAdminTodosRoute: AuthenticatedAdminTodosRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedClientProjectIdRoute: AuthenticatedClientProjectIdRoute,
  AuthenticatedClientNewRoute: AuthenticatedClientNewRoute,
  AuthenticatedEngineerProjectIdRoute:
    AuthenticatedEngineerProjectIdRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  AuthenticatedEngineerIndexRoute: AuthenticatedEngineerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
